"""LaTeX CV generation in the style of ``Resume.tex`` (the user's own template).

Pure text-building lives here: a renderer-agnostic cv-doc dict (see
``render.build_cv_doc``) is turned into a complete ``.tex`` document whose
preamble, macros, and section layout replicate the committed ``Resume.tex``
(extarticle 9pt, square bullets, blue ``\\repolink`` titles, EXPERIENCE →
EDUCATION → SKILLS → PROJECTS). Compilation is one subprocess call to whichever
LaTeX engine is on PATH (tectonic / xelatex / pdflatex — see
ACTIONS_FOR_PAUL.md); with no engine installed the ``.tex`` is still written and
the PDF is skipped, so the pipeline degrades gracefully.

Markdown that flows through tailoring (``**bold**`` emphasis, ``[text](url)``
links) is converted to ``\\textbf`` / ``\\href``; everything else is escaped, so
no résumé content can inject LaTeX.
"""

from __future__ import annotations

import re
import shutil
import subprocess
from pathlib import Path
from typing import Optional

from ..logging_config import get_logger

log = get_logger(__name__)

# Preamble copied from Resume.tex (macros, spacing, section rule) so the rendered
# PDF is indistinguishable in style from the hand-written original.
_PREAMBLE = r"""%------------------------
% Latex CV Template
% Author: Paul Litscher (generated by internship_pipeline)
%------------------------
\documentclass[a4paper,9pt]{extarticle}
\usepackage[utf8]{inputenc}
\usepackage[
    a4paper,
    top=0.55in,
    bottom=0.55in,
    left=0.6in,
    right=0.6in
]{geometry}
\usepackage{titlesec}
\usepackage{enumitem}
\usepackage{xcolor}
\usepackage{hyperref}
\hypersetup{
    colorlinks=true,
    urlcolor=black,
    linkcolor=black
}
\usepackage{changepage}
\usepackage{amssymb}
\usepackage{graphicx}

\definecolor{repoblue}{RGB}{30, 100, 180}
\newcommand{\repolink}[2]{\href{#1}{\textcolor{repoblue}{\textbf{#2}}}}
\newcommand{\sqbullet}{\raisebox{0.2ex}{\scalebox{0.6}{$\blacksquare$}}}
\newcommand{\jobspace}{\vspace{6pt}}
\linespread{1.05}

\setlength{\parskip}{2pt}
\setlength{\parindent}{0pt}

\setlist{
  noitemsep,
  topsep=2pt,
  parsep=0pt,
  partopsep=0pt,
  leftmargin=*
}
\titleformat{\section}
  {\normalsize\bfseries}
  {}
  {0pt}
  {}
  [\titlerule]
\titlespacing*{\section}{0pt}{6pt}{4pt}
\titlespacing*{\subsection}{0pt}{4pt}{2pt}

\begin{document}
\pagestyle{empty}
"""

_MD_LINK_RE = re.compile(r"\[([^\]]+)\]\(([^)\s]+)\)")
_MD_BOLD_RE = re.compile(r"\*\*(.+?)\*\*")

# Text-mode escapes, applied in ONE regex pass — sequential str.replace would
# re-escape the braces/backslashes inside earlier replacements.
_TEXT_ESCAPES: dict[str, str] = {
    "\\": r"\textbackslash{}",
    "&": r"\&",
    "%": r"\%",
    "$": r"\$",
    "#": r"\#",
    "_": r"\_",
    "{": r"\{",
    "}": r"\}",
    "~": r"\textasciitilde{}",
    "^": r"\textasciicircum{}",
    "<": r"\textless{}",
    ">": r"\textgreater{}",
}
_TEXT_ESCAPE_RE = re.compile("[" + re.escape("".join(_TEXT_ESCAPES)) + "]")

_ARROW_SENTINEL = "\x00ARROW\x00"


def latex_escape(text: str) -> str:
    """Escape plain text for LaTeX text mode (résumé content must never inject TeX)."""
    # Cosmetic: the ASCII arrow used in bullets ("S3 -> Glue") gets the real glyph,
    # matching the hand-written template's $\rightarrow$. Swapped out before the
    # character escapes (which would mangle the ">") and back in after them (which
    # would otherwise mangle the inserted TeX).
    out = (text or "").replace("->", _ARROW_SENTINEL)
    out = _TEXT_ESCAPE_RE.sub(lambda m: _TEXT_ESCAPES[m.group(0)], out)
    return out.replace(_ARROW_SENTINEL, r"$\rightarrow$")


def latex_escape_url(url: str) -> str:
    """Escape a URL for use inside ``\\href``/``\\repolink`` arguments.

    The URL passes through a macro argument (normal catcodes), so TeX-special
    characters must be backslash-escaped — hyperref maps ``\\%``/``\\#``/``\\&``/
    ``\\_`` back to the literal character in the link target.
    """
    out = (url or "").replace("\\", "").replace("{", "").replace("}", "")
    for char in ("%", "#", "&", "_"):
        out = out.replace(char, "\\" + char)
    return out


def md_to_latex(text: str) -> str:
    """Convert tailored-bullet Markdown (``**bold**``, ``[text](url)``) to LaTeX.

    Links become ``\\href`` (clickable in the PDF, same as the RenderCV output
    was); bold becomes ``\\textbf``; everything else is escaped.
    """

    def _bold_segment(segment: str) -> str:
        parts: list[str] = []
        last = 0
        for m in _MD_BOLD_RE.finditer(segment):
            parts.append(latex_escape(segment[last : m.start()]))
            parts.append(r"\textbf{" + latex_escape(m.group(1)) + "}")
            last = m.end()
        parts.append(latex_escape(segment[last:]))
        return "".join(parts)

    parts: list[str] = []
    last = 0
    for m in _MD_LINK_RE.finditer(text or ""):
        parts.append(_bold_segment((text or "")[last : m.start()]))
        parts.append(
            r"\href{" + latex_escape_url(m.group(2)) + "}{" + _bold_segment(m.group(1)) + "}"
        )
        last = m.end()
    parts.append(_bold_segment((text or "")[last:]))
    return "".join(parts)


_MONTHS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]


def format_date(value: Optional[str]) -> str:
    """``2025-01`` → ``Jan 2025``; ``present`` → ``Present``; anything else verbatim."""
    raw = (value or "").strip()
    if not raw:
        return ""
    if raw.lower() == "present":
        return "Present"
    m = re.fullmatch(r"(\d{4})-(\d{2})(?:-\d{2})?", raw)
    if m and 1 <= int(m.group(2)) <= 12:
        return f"{_MONTHS[int(m.group(2)) - 1]} {m.group(1)}"
    return raw


def format_date_range(start: Optional[str], end: Optional[str]) -> str:
    """``Jan 2025 -- Apr 2025`` (the template's en-dash range), tolerant of gaps."""
    left, right = format_date(start), format_date(end)
    if left and right:
        return f"{left} -- {right}"
    return left or right


def _linked_name(name: str) -> tuple[str, bool]:
    """An entry name that is entirely ``[text](url)`` → ``\\repolink``; else bold text.

    Returns ``(latex, is_link)`` so the header's blue-titles note is only shown
    when at least one repolink is actually on the page.
    """
    m = _MD_LINK_RE.fullmatch((name or "").strip())
    if m:
        return (
            r"\repolink{" + latex_escape_url(m.group(2)) + "}{" + latex_escape(m.group(1)) + "}",
            True,
        )
    return r"\textbf{" + md_to_latex(name) + "}", False


def _bullets_block(highlights: list[str]) -> str:
    items = "\n".join(r"      \item " + md_to_latex(h) for h in highlights)
    return (
        "    \\begin{itemize}[label=\\sqbullet, leftmargin=1.2em, topsep=0pt]\n"
        f"{items}\n"
        "    \\end{itemize}"
    )


def _social_url(network: str, username: str) -> tuple[str, str]:
    """(label, url) for the header links row, mirroring Resume.tex's link text."""
    if network == "LinkedIn":
        return "LinkedIn", f"https://linkedin.com/in/{username}/"
    if network == "GitHub":
        return "Github", f"https://github.com/{username}/"
    return network, username


def _header(cv: dict, *, show_repolink_note: bool) -> str:
    lines: list[str] = ["\\begin{center}"]
    lines.append("    \\textbf{\\Large " + latex_escape(cv.get("name", "")) + " }\\\\[2pt]")

    contact_bits = [latex_escape(cv[k]) for k in ("location", "phone") if cv.get(k)]
    if cv.get("email"):
        email = cv["email"]
        contact_bits.append(
            r"\href{mailto:" + latex_escape_url(email) + "}{" + latex_escape(email) + "}"
        )
    if contact_bits:
        lines.append("    \\textbf{" + " • ".join(contact_bits) + "}\\\\[1pt]")

    link_bits: list[str] = []
    for social in cv.get("social_networks", []):
        label, url = _social_url(social.get("network", ""), social.get("username", ""))
        link_bits.append(r"\href{" + latex_escape_url(url) + "}{" + latex_escape(label) + "}")
    if cv.get("website"):
        link_bits.append(
            r"\href{" + latex_escape_url(cv["website"]) + "}{Personal Website}"
        )
    if link_bits:
        lines.append("    " + " • ".join(link_bits) + "\\\\[2pt]")

    # Resume.tex has no summary section; the master résumé's summary (citizenship
    # etc.) is kept as one italic header line so the information isn't lost.
    summary = (cv.get("sections", {}).get("summary") or [""])[0]
    if summary:
        lines.append("    {\\small\\textit{" + md_to_latex(summary.strip()) + "}}\\\\[1pt]")

    if show_repolink_note:
        lines.append(
            "    {\\small\\textit{\\textcolor{repoblue}{\\textbf{Note:} "
            "Blue titles link to source repositories or live sites.}}}"
        )
    lines.append("\\end{center}")
    return "\n".join(lines)


def _experience_section(entries: list[dict]) -> str:
    blocks: list[str] = []
    for entry in entries:
        head = r"    \textbf{" + md_to_latex(entry.get("company", "")) + "}"
        if entry.get("location"):
            head += r" \hfill \textbf{" + latex_escape(entry["location"]) + "}"
        head += " \\\\\n"
        head += r"    \textbf{" + md_to_latex(entry.get("position", "")) + "}"
        dates = format_date_range(entry.get("start_date"), entry.get("end_date"))
        if dates:
            head += r" \hfill {\small " + latex_escape(dates) + "}"
        head += "\\par\n    \\vspace{-1pt}\n"
        blocks.append(head + _bullets_block(entry.get("highlights", [])))
    body = "\n\n    \\jobspace\n".join(blocks)
    return "\\section*{PROFESSIONAL EXPERIENCE}\n    \\noindent\n" + body


def _education_section(entries: list[dict]) -> str:
    blocks: list[str] = []
    for entry in entries:
        head = r"    \textbf{" + latex_escape(entry.get("institution", "")) + "}"
        if entry.get("location"):
            head += r" \hfill \textbf{" + latex_escape(entry["location"]) + "}"
        head += " \\\\\n"
        degree = " ".join(v for v in (entry.get("degree"), entry.get("area")) if v)
        head += "    {" + latex_escape(degree) + "}"
        dates = format_date_range(entry.get("start_date"), entry.get("end_date"))
        if dates:
            head += r" \hfill {\small " + latex_escape(dates) + "}"
        lines = [head]
        lines.extend("    " + md_to_latex(h) for h in entry.get("highlights", []))
        blocks.append(" \\\\\n".join(lines))
    return "\\section*{EDUCATION}\n" + "\n\n    \\jobspace\n".join(blocks)


def _skills_section(rows: list[dict]) -> str:
    lines = [
        "    {\\textbf{" + latex_escape(row.get("label", "")) + ":} "
        + latex_escape(row.get("details", "")) + "}\\\\"
        for row in rows
    ]
    return "\\section*{TECHNICAL SKILLS}\n" + "\n".join(lines)


def _projects_section(entries: list[dict]) -> tuple[str, bool]:
    any_link = False
    blocks: list[str] = []
    for entry in entries:
        name_latex, is_link = _linked_name(entry.get("name", ""))
        any_link = any_link or is_link
        head = "    " + name_latex
        dates = format_date_range(entry.get("start_date"), entry.get("end_date"))
        if dates:
            head += r" \hfill {\small " + latex_escape(dates) + "}"
        head += "\\par\n    \\vspace{-1pt}\n"
        blocks.append(head + _bullets_block(entry.get("highlights", [])))
    body = "\n\n    \\jobspace\n".join(blocks)
    return "\\section*{PROJECTS}\n" + body, any_link


def build_latex(cv_doc: dict) -> str:
    """The complete ``.tex`` document for one cv-doc, in Resume.tex's style/order."""
    cv = cv_doc.get("cv", {})
    sections = cv.get("sections", {})

    projects_tex, any_repolink = ("", False)
    if sections.get("projects"):
        projects_tex, any_repolink = _projects_section(sections["projects"])

    parts = [_PREAMBLE, _header(cv, show_repolink_note=any_repolink)]
    if sections.get("experience"):
        parts.append(_experience_section(sections["experience"]))
    if sections.get("education"):
        parts.append(_education_section(sections["education"]))
    if sections.get("skills"):
        parts.append(_skills_section(sections["skills"]))
    if projects_tex:
        parts.append(projects_tex)
    parts.append("\\end{document}\n")
    return "\n\n".join(parts)


# --- Compilation -------------------------------------------------------------

# Preference order: tectonic (self-contained, used in CI), then the TeX Live
# engines. Each maps to the argv that compiles `<slug>.tex` inside its own dir.
_ENGINES: tuple[str, ...] = ("tectonic", "xelatex", "pdflatex")


def find_latex_engine() -> Optional[str]:
    """The first available LaTeX engine on PATH, or None (PDF step is skipped)."""
    for engine in _ENGINES:
        if shutil.which(engine):
            return engine
    return None


def _engine_argv(engine: str, tex_name: str) -> list[str]:
    if engine == "tectonic":
        return ["tectonic", "--chatter", "minimal", tex_name]
    return [engine, "-interaction=nonstopmode", "-halt-on-error", tex_name]


def compile_latex(tex_path: str, *, engine: Optional[str] = None,
                  timeout: float = 180.0) -> Optional[str]:
    """Compile ``tex_path`` next to itself; return the PDF path or None.

    Best-effort by design (mirrors the old RenderCV behavior): a missing engine
    or failed compile logs a warning and returns None — the ``.tex``/YAML remain
    as the auditable artifacts.
    """
    engine = engine or find_latex_engine()
    tex = Path(tex_path)
    if engine is None:
        log.info("no LaTeX engine found; wrote .tex only", extra={"tex": str(tex)})
        return None
    try:
        proc = subprocess.run(
            _engine_argv(engine, tex.name),
            cwd=str(tex.parent),
            capture_output=True,
            text=True,
            timeout=timeout,
        )
    except (OSError, subprocess.SubprocessError) as exc:
        log.warning("LaTeX compile failed to run", extra={"engine": engine, "error": repr(exc)})
        return None
    pdf = tex.with_suffix(".pdf")
    if proc.returncode != 0 or not pdf.exists():
        log.warning(
            "LaTeX compile failed",
            extra={
                "engine": engine,
                "returncode": proc.returncode,
                "tail": ((proc.stderr or "") + (proc.stdout or ""))[-500:],
            },
        )
        return None
    return str(pdf)


_PAGES_COUNT_RE = re.compile(rb"/Type\s*/Pages[^>]*?/Count\s+(\d+)", re.DOTALL)
_COUNT_PAGES_RE = re.compile(rb"/Count\s+(\d+)[^>]*?/Type\s*/Pages", re.DOTALL)


def pdf_page_count(pdf_path: str) -> Optional[int]:
    """Number of pages, or None if it can't be determined.

    pypdf (the ``render`` extra) is the reliable path; the regex fallback reads
    the page-tree ``/Count`` and works on typical engine output, but returns
    None rather than guessing when the structure isn't visible (e.g. object
    streams).
    """
    try:
        from pypdf import PdfReader  # lazy: optional dependency

        return len(PdfReader(pdf_path).pages)
    except ImportError:
        pass
    except Exception as exc:
        log.warning("pypdf failed to read page count", extra={"error": repr(exc)})
        return None
    try:
        data = Path(pdf_path).read_bytes()
    except OSError:
        return None
    counts = [int(m.group(1)) for rx in (_PAGES_COUNT_RE, _COUNT_PAGES_RE)
              for m in rx.finditer(data)]
    return max(counts) if counts else None
